# Generated by Django 5.2.4 on 2025-08-02 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('flagged_rows', models.IntegerField(default=0)),
                ('clean_rows', models.IntegerField(default=0)),
                ('z_score_flagged', models.IntegerField(default=0)),
                ('iqr_flagged', models.IntegerField(default=0)),
                ('isolation_forest_flagged', models.IntegerField(default=0)),
                ('one_class_svm_flagged', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('is_flagged', models.BooleanField(default=False)),
                ('z_score_flag', models.BooleanField(default=False)),
                ('iqr_flag', models.BooleanField(default=False)),
                ('isolation_forest_flag', models.BooleanField(default=False)),
                ('one_class_svm_flag', models.BooleanField(default=False)),
                ('row_data', models.JSONField()),
                ('csv_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='detector.csvupload')),
            ],
        ),
    ]
