# Generated by Django 5.0.2 on 2025-09-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='row_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
