# Generated by Django 5.2.4 on 2025-11-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_alter_detectionresult_row_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='is_precleaned',
            field=models.BooleanField(default=False, help_text='Mark if this is an already-cleaned dataset (uses lenient thresholds)'),
        ),
    ]
